# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameras', models.CharField(max_length=2)),
                ('pantallas', models.CharField(max_length=2)),
                ('gabinetes', models.CharField(max_length=2)),
                ('salidas_analog', models.CharField(max_length=2)),
                ('salidas_dig', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ThermoGenius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('especification', models.ManyToManyField(to='cotizador.Especifications')),
            ],
        ),
    ]
