# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especifications',
            old_name='cameras',
            new_name='camaras',
        ),
    ]
