# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20180711_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especifications',
            name='camaras',
        ),
        migrations.RemoveField(
            model_name='especifications',
            name='gabinetes',
        ),
        migrations.RemoveField(
            model_name='especifications',
            name='pantallas',
        ),
        migrations.RemoveField(
            model_name='especifications',
            name='salidas_analog',
        ),
        migrations.RemoveField(
            model_name='especifications',
            name='salidas_dig',
        ),
        migrations.AddField(
            model_name='especifications',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermogenius',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thermo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermogenius',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
