# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_auto_20180711_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especifications',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='thermogenius',
            name='description',
            field=models.TextField(default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='thermogenius',
            name='especification',
            field=models.ManyToManyField(default='', to='cotizador.Especifications'),
        ),
        migrations.AlterField(
            model_name='thermogenius',
            name='image',
            field=models.ImageField(default='', upload_to='thermo'),
        ),
        migrations.AlterField(
            model_name='thermogenius',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='thermogenius',
            name='price',
            field=models.CharField(default='', max_length=7),
        ),
    ]
