# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_auto_20180711_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermogenius',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
